apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app-blue
  template:
    metadata:
      labels:
        app: nodejs-app-blue
    spec:
      containers:
      - name: nodejs-app
        image: bschmitt769/nodejs-express-app:0.4
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "blue"

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service-blue
spec:
  selector:
    app: nodejs-app-blue
  ports:
  - port: 80
    targetPort: 3000
    name: http
